
resolver: lts-9.21

packages:
- sbs-common
- sbs-jcstress
- sbs-main
- sbs-specjvm

extra-deps:
- github: wilton-iot/wilton-ffi
  commit: master

ghc-options:
  "$locals": -Wall -Werror
#  "$locals": -O2 -Wall -Werror
